# roles/ROLENAME/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_ROLENAME_namespace }}"
    - path: "{{ openio_ROLENAME_sysconfig_dir }}/{{ openio_ROLENAME_servicename }}"
    #- path: "{{ openio_ROLENAME_volume }}"
    #- path: "{{ openio_ROLENAME_pid_directory }}"
    - path: "/var/log/oio/sds/{{ openio_ROLENAME_namespace }}/{{ openio_ROLENAME_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "ROLENAME.conf.j2"
      dest: "{{ openio_ROLENAME_sysconfig_dir }}/\
        {{ openio_ROLENAME_servicename }}/{{ openio_ROLENAME_servicename }}.conf"
    - src: "gridinit_ROLENAME.conf.j2"
      dest: "{{ openio_ROLENAME_gridinit_dir }}/{{ openio_ROLENAME_gridinit_file_prefix }}\
        {{ openio_ROLENAME_servicename }}.conf"
  register: _ROLENAME_conf
  tags: configure

- name: restart ROLENAME
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_ROLENAME_namespace}}-{{openio_ROLENAME_servicename}}
  when:
    - _ROLENAME_conf.changed
    - not openio_ROLENAME_provision_only
  tags: configure
...
