---
- name: SAMBA - Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ samba_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags: install

- name: CTDB - packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ ctdb_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages_ctdb
  until: install_packages_ctdb is success
  retries: 5
  delay: 2
  when: openio_samba_ctdb
  tags: install

- name: Active Directory - packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ ad_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages_ad
  until: install_packages_ad is success
  retries: 5
  delay: 2
  when: openio_samba_active_directory
  tags: install
...
