---
- name: SAMBA - Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ samba_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2

- name: CTDB - packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ ctdb_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages_ctdb
  until: install_packages_ctdb is success
  retries: 5
  delay: 2
  when: openio_samba_ctdb
...
